# Generated by Django 2.0.2 on 2018-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_dbstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstudent',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
