# Generated by Django 2.0.2 on 2018-04-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Persons',
        ),
    ]
